name: Portfoy Takip Botu

on:
  schedule:
    - cron: '0 19 * * 1-5' # Hafta içi her gün TSİ 22:00
  workflow_dispatch:

jobs:
  run_bot:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Cek
        uses: actions/checkout@v3

      - name: Python Kur (3.10 Sarti)
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Kutuphaneleri Yukle
        run: |
          python -m pip install --upgrade pip
          pip install tefas-crawler pandas yfinance requests

      - name: Botu Calistir
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python main.py
